# https://github.com/actions/deploy-pages#usage
# https://nuxt.com/deploy/github-pages
name: Deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - .github/workflows/deploy.yml
      - posts-mini-app/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: posts-mini-app
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: pnpm install
      - name: build the app
        run: npx nuxt build --preset github_pages
        env:
          # for GitHub pages we want a simple Vue SPA
          NUXT_USE_SSR: 0
          # If you are not using a custom domain,
          # you need to set NUXT_APP_BASE_URL to your repository-slug
          # for your build step
          NUXT_APP_BASE_URL: '/example-nuxt-posts-app/'
      - name: Upload artifact to pages
        uses: actions/upload-pages-artifact@v3
        with:
          # this param needs to be from the content root
          # it doesn't know anything about the `working-directory` param
          path: ./posts-mini-app/.output/public

  # Deployment job
  deploy:
    # Add a dependency to the build job
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github_pages environment
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
